version: "3.8"
services:
  v2-frontend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: web
        PORT_PROGRAM: 8888:8888
    image: folio/v2-frontend
    container_name: folio_v2-frontend
    ports:
      - "8888:8888"
    networks:
      - traefik_default
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.v2-frontend.entrypoints=http"
      - "traefik.http.routers.v2-frontend.rule=Host(`trungthanhdev.com`)"
      - "traefik.http.routers.v2-frontend-secure.entrypoints=https"
      - "traefik.http.routers.v2-frontend-secure.rule=Host(`trungthanhdev.com`)"
      - "traefik.http.routers.v2-frontend-secure.tls.certresolver=letsencrypt"
networks:
  traefik_default:
    external: true
