name: Main workflow
on:
  push:
    branches:
      - main
env:
  WORKSPACE: /home/frontend
  PROJECT_NAME: folio
jobs:
  deploy:
    name: Go To Production
    runs-on: self-hosted
    steps:
      - name: If Folder Not Found Clone
        run: |
          if [ ! -d "$WORKSPACE/$PROJECT_NAME" ]; then
            git clone https://${{ secrets.GH_TOKEN }}@github.com/trungthanh12081997/$PROJECT_NAME.git $WORKSPACE/$PROJECT_NAME
          fi
        shell: bash

      - name: Deploy
        run: |
          echo "Deploying"
          cd "$WORKSPACE/$PROJECT_NAME"
          git config credential.helper '!f() { sleep 1; echo "username=${{ secrets.GH_USER }}"; echo "password=${{ secrets.GH_TOKEN }}"; }; f'
          git checkout main
          git reset --hard
          git pull --force
          docker rmi "$PROJECT_NAME" -f || true
          docker-compose up -d
        shell: bash
